# Generated by Django 5.2.6 on 2025-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(max_length=20)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('audio_link', models.CharField(blank=True, default='True', max_length=500, null=True)),
            ],
        ),
    ]
