# Generated by Django 5.2.6 on 2025-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
