# Generated by Django 5.2.6 on 2025-09-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzz', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, default='00:15:00', max_length=20, null=True),
        ),
    ]
