# Generated by Django 6.0 on 2025-12-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzz', '0004_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='synced_lyrics',
            field=models.JSONField(blank=True, help_text='Synchronized lyrics with timestamps in JSON format', null=True),
        ),
    ]
