# Generated by Django 5.2.5 on 2025-11-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buzz', '0004_alter_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics_text', models.TextField(help_text='Full lyrics text')),
                ('timestamps', models.JSONField(default=list, help_text="JSON array of objects with 'time' (in seconds) and 'text' fields")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synchronized_lyrics', to='Buzz.song')),
            ],
            options={
                'verbose_name_plural': 'Lyrics',
            },
        ),
    ]
